### ISSUE TITLE
Schließen Bild

### ISSUE THREAD

**Issue by ngdot** [fritzmg/contao-nivo-lightbox#1]
Hi,

das schließen Icon oben rechts in der Ecke ist ein Pfeil anstatt eines "X" Icons.

![bildschirmfoto 2015-09-24 um 08 24 06](https://cloud.githubusercontent.com/assets/8327905/10066715/da2cfa9c-6295-11e5-878f-78bb3cfdbbfc.png)

**Comment by fritzmg** [comment]
Hm, komisch. Hast du eine URL zu der Seite wo das pasiert?

**Comment by ngdot** [comment]
Habe den Fehler gefunden!
Es wird das richtige Bild geladen, allerdings wird es durch den Innenabstand und die Hintergrundposition abgeschnitten abgebildet. 

Richtig wäre:
.nivo-lightbox-theme-default .nivo-lightbox-close {
    display: block;
    background: url("../../system/modules/nivo_lightbox/assets/themes/default/close.png") no-repeat;
    width: 16px;
    height: 16px;
    text-indent: -9999px;
    opacity: 0.5; 
}

Anstatt: 

.nivo-lightbox-theme-default .nivo-lightbox-close {
    display: block;
    background: url("../../system/modules/nivo_lightbox/assets/themes/default/close.png") no-repeat 5px 5px;
    width: 16px;
    height: 16px;
    text-indent: -9999px;
    padding: 5px;
    opacity: 0.5;
}

**Comment by fritzmg** [comment]
Also auf Seiten wo nivo_lightbox eingebunden ist, ist dieses Verhalten nicht zu sehen. Außerdem verstehe ich nicht, wie deine Änderung überhaupt eine derartige Auswirkung auf das Bild hat, denn hinter `nivo_lightbox/assets/themes/default/close.png` verbirgt sich ja tatsächlich nur der close button und kein Pfeil.

**Comment by ngdot** [comment]
Der Pfeil ist kein gar kein Pfeil sondern ein Ausschnitt des "close.png".
Und der Fehler wird tatsächlich nicht von der Erweiterung generiert sondern durch eine andere CSS-Anweisung die in meinen Theme so hinterlegt war... 
- {
  box-sizing: border-box;
  }
  Kann also geschlossen werden, sorry für die Verwirrung!

**Comment by fritzmg** [comment]
Achsoo, haha. Ja, irgendwelche allgemeinen `box-sizing:border-box;` Anweisungen können gefährlich sein :). Und kein Problem.
