### ISSUE TITLE
Links to documentation are down

### ISSUE THREAD

**Issue by Aybee** [fritzmg/contao-nivo-lightbox#2]
Hello, those links http://docs.dev7studios.com/jquery-plugins/nivo-lightbox in the readme are down.

**Comment by fritzmg** [comment]
thx, see also https://github.com/Codeinwp/Nivo-Lightbox-jQuery/issues/59

**Comment by mlwebworker** [comment]
Auf der Suche nach der Doku bin ich über diesen Link gestolpert [https://themeisle.com/plugins/nivo-lightbox/]
Dort wird die gleiche Versionsnummer verwendet wie in Deiner Erweiterung, aber das Ganze steht scheinbar nicht mehr unter GNU zu Verfügung oder wie verstehst Du das?

Maren

**Comment by fritzmg** [comment]
Das bezieht sich nur auf das WordPress Plugin. Das war schon immer kommerziell. 

Im Repository des jQuery Plugins (https://github.com/Codeinwp/Nivo-Lightbox-jQuery) befindet sich immer noch die MIT Lizenz.

**Comment by fritzmg** [comment]
updated
